# Generated by Django 4.0.1 on 2022-03-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('F_V', 'Fruits and vegetables'), ('DA', 'Dairy'), ('FR', 'Frozen'), ('BK', 'Bakery'), ('M_F', 'Meat and fish'), ('CA', 'Canned'), ('SP', 'Spices'), ('DR', 'Dry'), ('PR', 'Premade'), ('O', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cooking_time', models.DurationField()),
                ('ingredient_ids', models.ManyToManyField(through='recipes_app.IngredientQuantity', to='recipes_app.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientquantity',
            unique_together={('ingredient_id',), ('recipe_id',)},
        ),
    ]
