# Generated by Django 4.0.3 on 2022-03-15 10:17

from django.db import migrations
import recipes_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_ingredient_name_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=recipes_app.models.NameField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=recipes_app.models.NameField(max_length=100, unique=True),
        ),
    ]
