# Generated by Django 4.0.3 on 2022-03-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_alter_ingredient_name_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='type',
            new_name='category',
        ),
    ]
