# Generated by Django 4.0.3 on 2022-03-17 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0004_rename_type_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
    ]
