# Generated by Django 4.0.3 on 2022-03-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientquantity',
            unique_together=set(),
        ),
    ]
