# Generated by Django 4.0.3 on 2022-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_alter_ingredientquantity_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'ingredient_id'), name='ingredient_unique_in_recipe'),
        ),
    ]
